## Assignment No: 9
## Name: Nghia Lam
## UTA ID: 1001699317

## INSTRUCTIONS 

Every learner should submit his/her own homework solutions. However, you are allowed to discuss the homework with each other– but everyone must submit his/her own solution; you may not copy someone else’s solution. 

Follow the prompts in the attached jupyter notebook. We are using a clean and modified version of the auto imports dataset (Description of the original dataset is in the cell bellow). Download the auto_imp.csv file from Canvas and put it in your working directory. Don't forget to add libraries to use in your analysis. You can use the code as a guide that was provided in the class. 

Add markdown cells to your analysis to include your solutions, comments, answers. Add as many cells as you need, for easy readability comment when possible. 

**Note:** You need to use your code from the previous assignment for question 1.

Submission: Run all your code cells and export the file as HTML. Submit a zip of your .ipynb file and HTML file. Add your name and UTA ID in the markdown cell above.

Good luck!



**Title: 1985 Auto Imports Database**

Relevant Information:
   -- Description
      This data set consists of three types of entities: (a) the
      specification of an auto in terms of various characteristics, (b)
      its assigned insurance risk rating, (c) its normalized losses in use
      as compared to other cars.  The second rating corresponds to the
      degree to which the auto is more risky than its price indicates.
      Cars are initially assigned a risk factor symbol associated with its
      price.   Then, if it is more risky (or less), this symbol is
      adjusted by moving it up (or down) the scale.  Actuarians call this
      process "symboling".  A value of +3 indicates that the auto is
      risky, -3 that it is probably pretty safe.

      The third factor is the relative average loss payment per insured
      vehicle year.  This value is normalized for all autos within a
      particular size classification (two-door small, station wagons,
      sports/speciality, etc...), and represents the average loss per car
      per year.

   -- Note: Several of the attributes in the database could be used as a
            "class" attribute.

5. Number of Instances: 205

6. Number of Attributes: 26 total
   -- 15 continuous
   -- 1 integer
   -- 10 nominal

7. Attribute Information:     
     Attribute:                Attribute Range:
     ------------------        -----------------------------------------------
  1. symboling:                -3, -2, -1, 0, 1, 2, 3.
  2. normalized-losses:        continuous from 65 to 256.
  3. make:                     alfa-romero, audi, bmw, chevrolet, dodge, honda,isuzu, jaguar, mazda, mercedes-benz, mercury, mitsubishi, nissan, peugot, plymouth, porsche, renault, saab, subaru, toyota,volkswagen, volvo
  4. fuel-type:                diesel, gas.
  5. aspiration:               std, turbo.
  6. num-of-doors:             four, two.
  7. body-style:               hardtop, wagon, sedan, hatchback, convertible.
  8. drive-wheels:             4wd, fwd, rwd.
  9. engine-location:          front, rear.
 10. wheel-base:               continuous from 86.6 120.9.
 11. length:                   continuous from 141.1 to 208.1.
 12. width:                    continuous from 60.3 to 72.3.
 13. height:                   continuous from 47.8 to 59.8.
 14. curb-weight:              continuous from 1488 to 4066.
 15. engine-type:              dohc, dohcv, l, ohc, ohcf, ohcv, rotor.
 16. num-of-cylinders:         eight, five, four, six, three, twelve, two.
 17. engine-size:              continuous from 61 to 326.
 18. fuel-system:              1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi.
 19. bore:                     continuous from 2.54 to 3.94.
 20. stroke:                   continuous from 2.07 to 4.17.
 21. compression-ratio:        continuous from 7 to 23.
 22. horsepower:               continuous from 48 to 288.
 23. peak-rpm:                 continuous from 4150 to 6600.
 24. city-mpg:                 continuous from 13 to 49.
 25. highway-mpg:              continuous from 16 to 54.
 26. price:                    continuous from 5118 to 45400.

8. Missing Attribute Values: (denoted by "?")

# 1. Preprocessing

In [11]:
## Add libraries to use
from numpy import where
from collections import Counter
from sklearn.datasets import make_blobs
from matplotlib import pyplot
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM
from sklearn.metrics import auc
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import SVC
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from collections import Counter
from sklearn.dummy import DummyClassifier
#from mlxtend.plotting import plot_confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np
from numpy import mean
import pandas as pd


**Use the dataset 'auto_imp.csv' from Canvas. Follow the prompts to complete the homework.**

In [12]:
df2 =pd.read_csv('auto_imp.csv')

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fuel_type    195 non-null    object 
 1   wheel_base   195 non-null    float64
 2   length       195 non-null    float64
 3   width        195 non-null    float64
 4   heights      195 non-null    float64
 5   curb_weight  195 non-null    int64  
 6   engine_size  195 non-null    int64  
 7   bore         195 non-null    float64
 8   stroke       195 non-null    float64
 9   comprassion  195 non-null    float64
 10  horse_power  195 non-null    int64  
 11  peak_rpm     195 non-null    int64  
 12  city_mpg     195 non-null    int64  
 13  highway_mpg  195 non-null    int64  
 14  price        195 non-null    int64  
dtypes: float64(7), int64(7), object(1)
memory usage: 23.0+ KB


## 1.1 **Replace ['gas', 'diesel'] string values to [0, 1]**

In [14]:
#Your code
df2=pd.get_dummies(df2, columns=['fuel_type'],drop_first=True, dtype=np.uint8)

In [15]:
df2

wheel_base  length  width  heights  curb_weight  engine_size  bore  \
0          88.6   168.8   64.1     48.8         2548          130  3.47   
1          88.6   168.8   64.1     48.8         2548          130  3.47   
2          94.5   171.2   65.5     52.4         2823          152  2.68   
3          99.8   176.6   66.2     54.3         2337          109  3.19   
4          99.4   176.6   66.4     54.3         2824          136  3.19   
..          ...     ...    ...      ...          ...          ...   ...   
190       109.1   188.8   68.9     55.5         2952          141  3.78   
191       109.1   188.8   68.8     55.5         3049          141  3.78   
192       109.1   188.8   68.9     55.5         3012          173  3.58   
193       109.1   188.8   68.9     55.5         3217          145  3.01   
194       109.1   188.8   68.9     55.5         3062          141  3.78   

     stroke  comprassion  horse_power  peak_rpm  city_mpg  highway_mpg  price  \
0      2.68          9.0          111      5000        21           27  13495   
1      2.68          9.0          111      5000        21           27  16500   
2      3.47          9.0          154      5000        19           26  16500   
3      3.40         10.0          102      5500        24           30  13950   
4      3.40          8.0          115      5500        18           22  17450   
..      ...          ...          ...       ...       ...          ...    ...   
190    3.15          9.5          114      5400        23           28  16845   
191    3.15          8.7          160      5300        19           25  19045   
192    2.87          8.8          134      5500        18           23  21485   
193    3.40         23.0          106      4800        26           27  22470   
194    3.15          9.5          114      5400        19           25  22625   

     fuel_type_gas  
0                1  
1                1  
2                1  
3                1  
4                1  
..             ...  
190              1  
191              1  
192              1  
193              0  
194              1  

[195 rows x 15 columns]

## 1.2 : Define your X and y: your dependent variable is fuel_type, the rest of the variables are your independent variables

In [16]:
#your code
y = df2['fuel_type_gas']
X = df2.drop(columns=['fuel_type_gas'])


## 1.3 Split your data into training and testing set. Use test_size=0.3, random_state=746 !

In [17]:
#your code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=746)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (136, 14)
X_test shape: (59, 14)
y_train shape: (136,)
y_test shape: (59,)


# 2. Classification

### 2.1 Use SVM to classify your data. Print/report your confusion matrix, classification report and AUC. What do you notice?

In [18]:
#your code
svm_class = SVC()
svm_class.fit(X_train,y_train)

y_pred = svm_class.predict(X_test)

conf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(conf_matrix)

class_report = classification_report(y_test,y_pred)
print("Classification Report:")
print(class_report)

auc = roc_auc_score(y_test,svm_class.decision_function(X_test))
print(f"AUC: {auc}")

Confusion Matrix:
[[ 0  9]
 [ 0 50]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.85      1.00      0.92        50

    accuracy                           0.85        59
   macro avg       0.42      0.50      0.46        59
weighted avg       0.72      0.85      0.78        59

AUC: 0.8577777777777778


C:\Users\nghia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nghia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nghia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### 2.2 Use Random Forest to classify your data. Print/report your confusion matrix, classification report and AUC. What do you notice?

In [19]:
#your code
rf_class = RandomForestClassifier(n_jobs=-1)
gs_rf = GridSearchCV(estimator=rf_class,
                     param_grid={'max_depth':np.arange(1,31)},
                     cv=5,
                     scoring='roc_auc')

model9=gs_rf.fit(X_train,y_train)
y_1 = gs_rf.predict(X_test)

rf_class.fit(X_train,y_train)

y_pred = rf_class.predict(X_test)

score = f1_score(y_test, y_1, pos_label=1)
print('F1 Score: %.3f' % score)

print(confusion_matrix(y_test, y_1))
print(classification_report(y_test, y_1))

print("Accuracy:",metrics.accuracy_score(y_test, y_1))

cohen=metrics.cohen_kappa_score(y_test, y_1)
print('Cohen Kappa: %.3f' % cohen)

auc_score = roc_auc_score(y_test, y_1)

print('AUC: %.3f' % auc_score)

F1 Score: 0.926
[[ 1  8]
 [ 0 50]]
              precision    recall  f1-score   support

           0       1.00      0.11      0.20         9
           1       0.86      1.00      0.93        50

    accuracy                           0.86        59
   macro avg       0.93      0.56      0.56        59
weighted avg       0.88      0.86      0.82        59

Accuracy: 0.864406779661017
Cohen Kappa: 0.175
AUC: 0.556


### 2.3 Compare your results from Assignment 8 and Asisgnment 9 to comment on your findings. Which one(s) did the best job ? What could have been the problem with the ones that did not work? etc.

For both assignment 8 and 9 there was alot of classification that had very good accuracy. I believe that because there is not enough data the accuracy is very high so to change this more data would be needed to check but if we were to pick Naive bayes and logistic would be my pick as they would have the highest probability.

### 3. Try to fix the inbalanced nature of the data with a tool from the lecture. Run one of the classification methods (preferable one that "failed" before) and see if you get better results.

In [20]:
#pip install --upgrade pyodbc

In [21]:
#!pip install imbalanced-learn

In [28]:
#your code
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=50)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

svc_model = SVC(random_state=50)
svc_model.fit(X_train_smote, y_train_smote)

# Making predictions
predictions = svc_model.predict(X_test)

# Evaluating the model
print('Accuracy:', accuracy_score(y_test, predictions))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, predictions))
print('\nClassification Report:\n', classification_report(y_test, predictions))

Accuracy: 0.6610169491525424

Confusion Matrix:
 [[ 4  5]
 [15 35]]

Classification Report:
               precision    recall  f1-score   support

           0       0.21      0.44      0.29         9
           1       0.88      0.70      0.78        50

    accuracy                           0.66        59
   macro avg       0.54      0.57      0.53        59
weighted avg       0.77      0.66      0.70        59



Over sampling for SVC gives a lower accuracy, it seems like oversampling does not work with this classification. 